name: Build ImageSnapPurge Executable

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow imagehash
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: List files
      run: dir
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name ImageSnapPurge duplicados.py
        
    - name: Check if executable was created
      run: if exist dist\ImageSnapPurge.exe (echo "Executable created successfully") else (echo "Executable not found" && exit 1)
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ImageSnapPurge-Windows
        path: dist/ImageSnapPurge.exe

  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libxcb-cursor0 libxcb-xinerama0 libxcb-xfixes0
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow imagehash
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: List files
      run: ls -la
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name ImageSnapPurge duplicados.py
        
    - name: Check if executable was created
      run: |
        if [ -f dist/ImageSnapPurge ]; then
          echo "Executable created successfully"
        else
          echo "Executable not found"
          exit 1
        fi
        
    - name: Set executable permissions
      run: chmod +x dist/ImageSnapPurge
      
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: ImageSnapPurge-Linux
        path: dist/ImageSnapPurge

  build-macos:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow imagehash
        
    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: List files
      run: ls -la
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name ImageSnapPurge duplicados.py
        
    - name: Check if executable was created
      run: |
        if [ -f dist/ImageSnapPurge ]; then
          echo "Executable created successfully"
        else
          echo "Executable not found"
          exit 1
        fi
        
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: ImageSnapPurge-macOS
        path: dist/ImageSnapPurge

  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/ImageSnapPurge-Windows/ImageSnapPurge.exe
          artifacts/ImageSnapPurge-Linux/ImageSnapPurge
          artifacts/ImageSnapPurge-macOS/ImageSnapPurge
        body: |
          # ImageSnapPurge v${{ github.ref_name }}
          
          ## Descargas
          
          - **ImageSnapPurge.exe**: Ejecutable para Windows
          - **ImageSnapPurge**: Ejecutable para Linux
          - **ImageSnapPurge**: Ejecutable para macOS
          
          ## Instrucciones
          
          1. Descarga el ejecutable correspondiente a tu sistema operativo
          2. Ejecuta ImageSnapPurge (o ImageSnapPurge.exe en Windows)
          3. ¡Disfruta de una colección de imágenes libre de duplicados!
          
          ## Características
          
          - ✅ Detección inteligente de duplicados
          - ✅ Interfaz moderna y fácil de usar
          - ✅ Eliminación segura (recuperable desde papelera)
          - ✅ Múltiples niveles de similitud
          - ✅ Vista previa de miniaturas
          - ✅ Auto-selección inteligente
        draft: false
        prerelease: false

  create-draft-release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: ImageSnapPurge - Latest Build
        files: |
          artifacts/ImageSnapPurge-Windows/ImageSnapPurge.exe
          artifacts/ImageSnapPurge-Linux/ImageSnapPurge
          artifacts/ImageSnapPurge-macOS/ImageSnapPurge
        body: |
          # ImageSnapPurge - Build Latest
          
          **Commit:** ${{ github.sha }}
          **Branch:** ${{ github.ref_name }}
          **Fecha:** ${{ github.event.head_commit.timestamp }}
          
          ## Descargas
          
          - **ImageSnapPurge.exe**: Ejecutable para Windows
          - **ImageSnapPurge**: Ejecutable para Linux
          - **ImageSnapPurge**: Ejecutable para macOS
          
          ## Instrucciones
          
          1. Descarga el ejecutable correspondiente a tu sistema operativo
          2. Ejecuta ImageSnapPurge (o ImageSnapPurge.exe en Windows)
          3. ¡Disfruta de una colección de imágenes libre de duplicados!
          
          ## Características
          
          - ✅ Detección inteligente de duplicados
          - ✅ Interfaz moderna y fácil de usar
          - ✅ Eliminación segura (recuperable desde papelera)
          - ✅ Múltiples niveles de similitud
          - ✅ Vista previa de miniaturas
          - ✅ Auto-selección inteligente
          
          **Nota:** Este es un build automático de la rama principal. Para una versión estable, espera a que se publique un release oficial.
        draft: true
        prerelease: true