name: Build ImageSnapPurge Executable

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 Pillow imagehash pyinstaller
        
    - name: List files in directory
      run: dir
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name ImageSnapPurge --hidden-import PyQt5.sip --hidden-import PyQt5.QtCore --hidden-import PyQt5.QtGui --hidden-import PyQt5.QtWidgets duplicados.py
      
    - name: Check if executable was created
      shell: cmd
      run: |
        if exist dist\ImageSnapPurge.exe (
            echo "Executable created successfully"
            dir dist\
        ) else (
            echo "Executable not found"
            dir dist\
            exit 1
        )
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: ImageSnapPurge-Windows
        path: dist/ImageSnapPurge.exe